// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag="1")]
    pub block: ::core::option::Option<BlockRef>,
    #[prost(message, optional, tag="2")]
    pub transaction: ::core::option::Option<TransactionRef>,
    #[prost(message, optional, tag="3")]
    pub log: ::core::option::Option<LogRef>,
    #[prost(enumeration="DataSource", tag="4")]
    pub source: i32,
    #[prost(oneof="event::Payload", tags="10, 11, 12, 13, 14, 15, 16")]
    pub payload: ::core::option::Option<event::Payload>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag="10")]
        Initialize(super::Initialize),
        #[prost(message, tag="11")]
        ModifyLiquidity(super::ModifyLiquidity),
        #[prost(message, tag="12")]
        Swap(super::Swap),
        #[prost(message, tag="13")]
        Subscription(super::Subscription),
        #[prost(message, tag="14")]
        Unsubscription(super::Unsubscription),
        #[prost(message, tag="15")]
        Transfer(super::Transfer),
        #[prost(message, tag="16")]
        LogCreatePrivateHook(super::LogCreatePrivateHook),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockRef {
    #[prost(uint64, tag="1")]
    pub number: u64,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="4")]
    pub timestamp_seconds: i64,
    #[prost(int32, tag="5")]
    pub timestamp_nanos: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRef {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(bytes="vec", tag="2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub origin: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub to: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogRef {
    #[prost(uint32, tag="1")]
    pub transaction_log_index: u32,
    #[prost(uint32, tag="2")]
    pub block_log_index: u32,
    #[prost(uint64, tag="3")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="4")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub graph_node_trigger_order: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="4")]
    pub fee: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub tick_spacing: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub hooks: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="7")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub tick: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModifyLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub tick_lower: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tick_upper: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub liquidity_delta: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub amount0: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount1: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub tick: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Subscription {
    #[prost(string, tag="1")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub subscriber: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unsubscription {
    #[prost(string, tag="1")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub subscriber: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub token_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogCreatePrivateHook {
    #[prost(bytes="vec", tag="1")]
    pub hook: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub module: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataSource {
    Unspecified = 0,
    PoolManager = 1,
    PositionManager = 2,
    ArrakisHookFactory = 3,
}
impl DataSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DataSource::Unspecified => "DATA_SOURCE_UNSPECIFIED",
            DataSource::PoolManager => "DATA_SOURCE_POOL_MANAGER",
            DataSource::PositionManager => "DATA_SOURCE_POSITION_MANAGER",
            DataSource::ArrakisHookFactory => "DATA_SOURCE_ARRAKIS_HOOK_FACTORY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_SOURCE_POOL_MANAGER" => Some(Self::PoolManager),
            "DATA_SOURCE_POSITION_MANAGER" => Some(Self::PositionManager),
            "DATA_SOURCE_ARRAKIS_HOOK_FACTORY" => Some(Self::ArrakisHookFactory),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
